### PR TITLE
Template Improvement and Documentation

### PR DESCRIPTION
**Pull request by Cossey**
I have made a bunch of improvements to the template includes and the Sitemap Page. New task to assist with Showing and Hiding Pages in the Sitemap. Also created documentation.

*This is my first ever Pull request.*

### CODE REVIEW

**Comment by xini** [comment]
Hi @Cossey Thanks for the PR. I'll review and get back to you. Cheers

**Comment by xini** [comment]
Hi @Cossey,

Sorry it has taken me so long to get back to you.

I am happy with most of the changes. Two things I'd like you to be changed:

- When the `$Sitemap` variable is not available in the Content, you render the sitemap into `$Form`. I'd rather append the sitemap to the content instead, the $Form variable might be at a completely different location in the layout. Also, I think it is confusing when a sitemap gets rendered in the Form variable.
- I think the template `templates/sitemap/SiteMapContentPreview.ss` should be made recursive as well. You've done that beautifully for `templates/sitemap/SiteMapDefault.ss` and I think it would be good to be consistent.

Would you be able to update this? Happy to merge once done.

Cheers

**Comment by xini** [comment]
Sorry, one more thought:
What happens when someone has an explicit <% include Sitemap %> in their theme? In that case, the sitemap shouldn't be rendered in $Content nor $Form.

**Comment by Cossey** [comment]
Thanks for reviewing this PR, in response to your queries:
- I agree regarding the`$Form` variable - I will make it append to end of the content when `$Sitemap` is omitted as that makes sense. 
- I'll also improve both templates further and make the other one recursive.
- The reasoning behind allowing includes and Sitemap tags on a sitemap page was the idea to allow multiple sitemap pages which can have differing starting nodes for differing sections on a website however I don't believe I got the chance to implement this part.

_I can make the changes and commit them for another review but my dev VPS is down at the moment so it'll take a little longer than usual._

**Comment by xini** [comment]
no problem. thanks!

**Comment by xini** [comment]
It's been a long time. I'm closing this.

**Pull request closed without merging**
